### ISSUE TITLE
t/basic.t started to fail

### ISSUE THREAD

**Issue by eserte** [kberov/Mojolicious-Plugin-RoutesConfig#1]
On most of my smoker systems I see the following new test failure:
```
t/basic.t ........ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```
Reason is unknown.

**Comment by eserte** [comment]
Mojolicious::Plugin::PODRenderer was removed in Mojolicious 8.12, so probably it fails if it was not previously installed.

**Comment by kberov** [comment]
Fixed
